service: api
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # TODO change
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: '--enable-source-maps'

params:
  default:
    esbuildMinify: true
    esbuildExclude:
      - aws-sdk
  local:
    esbuildMinify: false
    esbuildExclude: []

custom:
  stages:
    - local
    - dev
    - prod
  stage: ${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: ${param:esbuildMinify}
    sourcemap: true
    keepNames: true
    watch:
      pattern:
        - 'src/**/*.ts'
    exclude: ${param:esbuildExclude}

functions:
  # authentication module
  auth:
    handler: src/infra/routes/auth/index.POST
    events:
      - httpApi:
          path: /auth
          method: post
  # users module
  createUser:
    handler: src/infra/routes/users/index.POST
    events:
      - httpApi:
          path: /users
          method: post
  # transactions module
  createTransaction:
    handler: src/infra/routes/transactions/index.POST
    events:
      - httpApi:
          path: /transactions
          method: post
